#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ .
    DIRECTORY_SEPARATOR .
    'bootstrap' .
    DIRECTORY_SEPARATOR .
    'app.php';

$status = $app->handleCommand();

exit($status);
